# Site settings
title: Lion Dynamics
email: 
url: https://liondynamics.io
description: "Build on Ethereum.
Collaborate worldwide."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fc0'

# Footer settings
footer: Lion Dynamics

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/liondynamics
  - title: github
    url: https://github.com/liondynamics

# Build settings
markdown: kramdown
permalink: pretty
